import { OrderItem, Payment } from '@prisma/client';
import PDFDocument from 'pdfkit';
import { formatMoney } from '../../common/utils/money';

/** The order shape the invoice renderer needs (items + payment included). */
export interface InvoiceOrder {
  orderNumber: string;
  email: string;
  currency: string;
  subtotalCents: number;
  discountCents: number;
  shippingCents: number;
  taxCents: number;
  totalCents: number;
  status: string;
  createdAt: Date;
  paidAt: Date | null;
  shippingSnapshot: unknown;
  items: OrderItem[];
  payment: Payment | null;
}

interface AddressLike {
  fullName?: string;
  line1?: string;
  line2?: string | null;
  city?: string;
  state?: string | null;
  postalCode?: string;
  country?: string;
  phone?: string | null;
}

/**
 * Render a PDF invoice for an order and resolve to the full Buffer.
 * Layout is intentionally simple and dependency-light (pdfkit only).
 */
export function generateInvoicePdf(order: InvoiceOrder): Promise<Buffer> {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ size: 'A4', margin: 50 });
    const chunks: Buffer[] = [];

    doc.on('data', (chunk: Buffer) => chunks.push(chunk));
    doc.on('end', () => resolve(Buffer.concat(chunks)));
    doc.on('error', reject);

    const currency = order.currency || 'INR';
    const money = (cents: number) => formatMoney(cents, currency);

    // Header
    doc.fontSize(22).fillColor('#0f172a').text('HashTag Creations', { continued: false });
    doc.fontSize(10).fillColor('#64748b').text('3D-printed products', { continued: false });
    doc.moveDown(0.5);
    doc.fontSize(16).fillColor('#0f172a').text(`Invoice ${order.orderNumber}`);
    doc
      .fontSize(10)
      .fillColor('#64748b')
      .text(`Status: ${order.status}`)
      .text(`Order date: ${order.createdAt.toISOString().slice(0, 10)}`);
    if (order.paidAt) doc.text(`Paid: ${order.paidAt.toISOString().slice(0, 10)}`);
    doc.moveDown(1);

    // Bill-to
    const ship = (order.shippingSnapshot ?? {}) as AddressLike;
    doc.fontSize(12).fillColor('#0f172a').text('Ship to');
    doc.fontSize(10).fillColor('#334155');
    if (ship.fullName) doc.text(ship.fullName);
    doc.text(order.email);
    if (ship.line1) doc.text(ship.line1);
    if (ship.line2) doc.text(ship.line2);
    const cityLine = [ship.city, ship.state, ship.postalCode].filter(Boolean).join(', ');
    if (cityLine) doc.text(cityLine);
    if (ship.country) doc.text(ship.country);
    doc.moveDown(1);

    // Line-item table
    const tableTop = doc.y;
    const colItem = 50;
    const colQty = 330;
    const colUnit = 390;
    const colTotal = 480;

    doc.fontSize(10).fillColor('#0f172a');
    doc.text('Item', colItem, tableTop);
    doc.text('Qty', colQty, tableTop);
    doc.text('Unit', colUnit, tableTop);
    doc.text('Total', colTotal, tableTop);
    doc
      .moveTo(colItem, tableTop + 15)
      .lineTo(545, tableTop + 15)
      .strokeColor('#e2e8f0')
      .stroke();

    let y = tableTop + 22;
    doc.fillColor('#334155');
    for (const item of order.items) {
      const label = item.customText ? `${item.nameSnapshot} — "${item.customText}"` : item.nameSnapshot;
      doc.text(label, colItem, y, { width: colQty - colItem - 10 });
      doc.text(String(item.quantity), colQty, y);
      doc.text(money(item.unitPriceCents), colUnit, y);
      doc.text(money(item.totalCents), colTotal, y);
      y = Math.max(y + 18, doc.y + 4);
    }

    doc
      .moveTo(colItem, y + 2)
      .lineTo(545, y + 2)
      .strokeColor('#e2e8f0')
      .stroke();
    y += 12;

    // Totals
    const totalsLabel = colUnit;
    const writeTotal = (label: string, cents: number, bold = false) => {
      doc.fontSize(10).fillColor(bold ? '#0f172a' : '#334155');
      doc.text(label, totalsLabel, y);
      doc.text(money(cents), colTotal, y);
      y += 16;
    };
    writeTotal('Subtotal', order.subtotalCents);
    if (order.discountCents > 0) writeTotal('Discount', -order.discountCents);
    writeTotal('Shipping', order.shippingCents);
    writeTotal('GST (18%)', order.taxCents);
    writeTotal('Total', order.totalCents, true);

    doc.moveDown(2);
    doc
      .fontSize(9)
      .fillColor('#94a3b8')
      .text('Thank you for your order. This invoice was generated by HashTag Creations.', colItem, doc.y, {
        width: 495,
      });

    doc.end();
  });
}
